In [1]:
import multiprocessing as mp
import time
import os
import gc

import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import log_loss, auc, roc_curve, f1_score, average_precision_score, mean_squared_error
from sklearn.model_selection import StratifiedKFold
import catboost as cat

from reduce_memory import reduce_numeric_mem_usage, reduce_object_mem_usage

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [17]:
sub_sample = pd.read_csv('./data/submission_popular.csv')

In [2]:
test_pred = pd.read_csv('./data/sub.csv')

In [27]:
test = pd.read_csv('./data/test.csv')

In [3]:
test_pred.head()

,user_id,session_id,timestamp,step,item_recommendations,recommendation
0,000324D9BBUC,89643988fdbfb,1541593942,10,924795 106315 1033140 119494 101758 903037 105...,923407 1050792 106315 97171 924795 353141 1033...
1,0004Q49X39PY,9de47d9a66494,1541641157,1,3505150 3812004 2227896 2292254 3184842 222702...,2213014 3184842 3812004 3505150 10213134 22922...
2,0004Q49X39PY,beea5c27030cb,1541561202,1,4476010 3505150 3812004 2227896 2292254 222702...,3812004 3505150 2292254 4476010 7101352 222789...
3,00071784XQ6B,9617600e1ba7c,1541630328,2,22854 3067559 22721 22713 16121 22772 22727 22...,22854 22721 3067559 16121 22764 22819 22713 22...
4,0008BO33KUQ0,2d0e2102ee0dc,1541636411,6,9857656 5849628 655716 1352530 502066 1405084 ...,507861 2176280 1669587 9857656 4272108 502066 ...

In [72]:
test_pred.drop('item_recommendations', axis=1, inplace=True)

In [75]:
test_pred.rename(columns={'recommendation': 'item_recommendations'}, inplace=True)

In [76]:
test_pred.to_csv('first_sub.csv', index=False)

In [4]:
test_pred.iloc[0]['item_recommendations']

'924795 106315 1033140 119494 101758 903037 1050792 97171 353141 2094950 923407 106307 1000915 97170 147907 1838901 1729121 2182130 904851 927351 4234718 2358690 2431104 1241375 152107'

In [5]:
test_pred.iloc[0]['recommendation']

'923407 1050792 106315 97171 924795 353141 1033140 2094950 106307 903037 1000915 1838901 119494 1241375 147907 101758 97170 1729121 2182130 4234718 927351 2358690 904851 152107 2431104'

In [10]:
sub_sample.to_csv('submission.csv', index=False)

---

In [69]:
test.reference.nunique()

184878

In [ ]:
def output_impressions(df):
    pred_list = df['pred'].values
    sorted_ind = np.argsort(pred_list)[::-1]
    ranked_items = list(df['item_id'].iloc[sorted_ind].values)
    ranked_items_str = [str(i) for i in ranked_items]
    return ' '.join(ranked_items_str)
xtest['pred'] = np.random.randint(0,2, len(xtest))

In [ ]:
test_imps_pred = xtest.groupby(level=0).apply(output_impressions)
#     test_imps_pred = xtest.groupby(level=0).apply(output_impressions)
test_imps_pred = test_imps_pred.reset_index(name='recommendation')

In [ ]:
test_imps_pred.head()

In [ ]:
sub = pd.read_csv('./data/submission_popular.csv')

In [ ]:
sub.head()

In [ ]:
subs = pd.merge(sub, test_imps_pred, how='left', on='session_id')

In [ ]:
subs.head()

In [ ]:
set(test_imps_pred.session_id).intersection(subs.user_id)

In [ ]:
set(xtest.session_id).intersection(subs.session_id)

In [ ]:
xtest.index

In [ ]:
test = pd.read_csv('./data/test.csv')

In [ ]:
test.head()

In [ ]:
test[test.session_id=='1d688ec168932']

In [ ]:
len(sub)

In [ ]:
sub.session_id.isin(test.session_id).sum()

In [ ]:
len(subs)

In [ ]:
xtest[xtest.session_id=='89643988fdbfb']

In [ ]:
sub_sample[sub_sample.session_id=='89643988fdbfb']

In [ ]:
xval = pd.read_hdf('./data/train.h5', key='xval')

In [ ]:
xval.head()

In [ ]:
%%time
train = pd.read_csv('./data/train.csv')

In [ ]:
train.head()

In [ ]:
xval.head()

In [ ]:
xval.session_id.isin(train.session_id).sum()

In [ ]:
xval.shape

In [11]:
tc = pd.read_csv('./test_click.csv')

In [12]:
tc.head()

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,ts
0,P2L70S1Y60IF,0000059a39020,1541719950,1,clickout item,NaN,JP,"Sapporo, Japan",mobile,NaN,2251200|924581|4775012|10090928|2282660|895299...,54|42|64|51|62|42|61|54|53|56|54|53|57|59|44|4...,2018-11-08 23:32:30
1,SKDEGHT3I151,0000b9394297b,1541606075,1,search for poi,Sassi di Matera,AR,"Matera, Italy",mobile,NaN,NaN,NaN,2018-11-07 15:54:35
2,SKDEGHT3I151,0000b9394297b,1541606244,2,clickout item,NaN,AR,"Matera, Italy",mobile,NaN,1044228|5670638|5875672|6033244|7917004|507857...,242|193|288|180|196|129|155|232|245|191|188|17...,2018-11-07 15:57:24
3,VEGQ0VOVB802,0000e0500c2e7,1541585429,1,clickout item,3844380,IN,"Saputara, India",mobile,NaN,6688304|3844380|1542171|3793522|2656440|260528...,46|25|48|71|132|44|71|8|32|57|54|66|57|33|57|7...,2018-11-07 10:10:29
4,VEGQ0VOVB802,0000e0500c2e7,1541585739,2,clickout item,9387530,IN,"Saputara, India",mobile,NaN,6688304|3844380|1542171|3793522|2656440|260528...,46|25|48|71|132|44|71|8|32|57|54|66|57|33|57|7...,2018-11-07 10:15:39

In [13]:
tc.groupby('session_id').tail(1)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,ts
0,P2L70S1Y60IF,0000059a39020,1541719950,1,clickout item,NaN,JP,"Sapporo, Japan",mobile,NaN,2251200|924581|4775012|10090928|2282660|895299...,54|42|64|51|62|42|61|54|53|56|54|53|57|59|44|4...,2018-11-08 23:32:30
2,SKDEGHT3I151,0000b9394297b,1541606244,2,clickout item,NaN,AR,"Matera, Italy",mobile,NaN,1044228|5670638|5875672|6033244|7917004|507857...,242|193|288|180|196|129|155|232|245|191|188|17...,2018-11-07 15:57:24
4,VEGQ0VOVB802,0000e0500c2e7,1541585739,2,clickout item,9387530,IN,"Saputara, India",mobile,NaN,6688304|3844380|1542171|3793522|2656440|260528...,46|25|48|71|132|44|71|8|32|57|54|66|57|33|57|7...,2018-11-07 10:15:39
5,V3SQM6X57BNX,0001650138d30,1541614783,1,clickout item,NaN,CA,"Banff, Canada",mobile,NaN,44394|44103|44247|44155|43972|44292|44404|4449...,259|220|99|210|283|252|152|192|179|213|199|175...,2018-11-07 18:19:43
9,13UA01X5MOHZ,000177b850519,1541574580,4,clickout item,NaN,TR,"Rome, Italy",desktop,NaN,17011|16122|17403|17040|17266|17295|17535|1757...,875|726|216|396|263|174|182|264|327|265|364|27...,2018-11-07 07:09:40
20,K0LALBSISIAC,00017b3b2c136,1541565393,11,clickout item,NaN,CO,"Piedecuesta, Colombia",mobile,NaN,5723818|4341718|6298194|6698142|7952264|285957...,46|89|21|14|59|74|37|33|30|46|17|77|12|37|44|3...,2018-11-07 04:36:33
26,51BGO9LGJDHT,0001d7853e07d,1541704166,6,clickout item,NaN,IE,"Killarney, Ireland",tablet,NaN,19822|854066|888605|19821|19820|906385|485171|...,115|59|89|95|134|220|110|89|119|190|143|195|10...,2018-11-08 19:09:26
27,0ROCDBG2IZEE,000227a856f46,1541644962,1,clickout item,NaN,IN,"Dapoli, India",mobile,NaN,2667568|3825952|2661488|6940638|9793448|977722...,92|43|61|250|48|34|10|27|36|274|52|463|110,2018-11-08 02:42:42
28,KER7PAE786J1,000243bb22a50,1541612425,1,clickout item,NaN,DE,"Paris, France",mobile,NaN,49536|149808|2418418|1122314|149795|5502530|62...,82|40|44|48|49|49|52|52|55|55|56|56|56|58|58|5...,2018-11-07 17:40:25
61,2U7433585MSR,000246890bfc6,1541717372,33,clickout item,NaN,NZ,"Wellington, New Zealand",tablet,Sort by Price,1257157|7845384|2743534|1276700|1276698|790286...,32|40|47|49|50|61|63|64|71|74|76|83|85|86|87|8...,2018-11-08 22:49:32
62,2MOD249K72Q0,00025aab42e55,1541621623,1,clickout item,NaN,ES,"Arcos de la Frontera, Spain",tablet,NaN,156147|156768|179771|1887875|1095378|156777|11...,44|75|45|65|176|50|63|99|45|33|40|51|43|32|35|...,2018-11-07 20:13:43
63,2LWWE5HA9CS5,0002b6d9d3bed,1541594477,1,clickout item,NaN,BR,"Maragogi, Brazil",mobile,NaN,3094482|1668489|1677213|5965972|2710052|185902...,283|84|71|116|44|97|97|122|72|124|44|89|41|60|...,2018-11-07 12:41:17
65,4OVH94GYTW96,0003005fe4aa2,1541603176,2,clickout item,NaN,PL,"Poznań, Poland",mobile,NaN,2418986|3144262|5504576|163780|163765|129140|5...,61|59|70|84|49|64|54|38|51|156|48|74|39|48|62|...,2018-11-07 15:06:16
83,V2O3K2WD3A9C,000305995c580,1541691430,18,interaction item image,155800,DE,"Frankfurt, Germany",mobile,NaN,NaN,NaN,2018-11-08 15:37:10
85,8795DDLCTTEC,0003377e48844,1541584240,2,interaction item rating,54727,US,"Brussels, Belgium",mobile,NaN,NaN,NaN,2018-11-07 09:50:40
90,Z7BDMNH489W9,000338c4794e8,1541615143,5,clickout item,NaN,CO,"Jericó, Colombia",desktop,NaN,3953190|8268290|10598542|5060264|5574632|58870...,53|56|33|44|49|60|72|36|21|51|13|39,2018-11-07 18:25:43
112,XGI7FO4684RI,00035287b3cd6,1541720920,22,clickout item,NaN,IT,"Marrakech, Morocco",mobile,NaN,449196|97916|6862392|97938|841371|1947551|2455...,55|102|119|134|69|59|54|316|206|129|46|86|54|7...,2018-11-08 23:48:40
116,22GK43YL6FFP,000356259e25a,1541554000,4,clickout item,NaN,MX,"Acapulco, Mexico",mobile,NaN,948643|34338|18230|100302|1538159|42402|42363|...,93|64|279|97|180|92|66|58|125|47|279|293|122|5...,2018-11-07 01:26:40
117,RB9GGD1O9NS1,00039ba18d20b,1541704208,1,interaction item rating,NaN,AU,"Melbourne, Australia",mobile,NaN,NaN,NaN,2018-11-08 19:10:08
133,BUWUOTQJ47Y6,0003ce539baa5,1541708357,16,clickout item,NaN,US,"Corpus Christi, USA",mobile,Focus on Rating,68074|63002|63935|836511|63637|843441|76320|36...,74|79|76|96|97|97|87|179|52|80|440|67|76|105|8...,2018-11-08 20:19:17
135,K66H3E6Z2FO1,0003e88695444,1541679935,2,clickout item,NaN,FR,"Toulon, France",mobile,NaN,2634820|1323316|7681746|716676|8317502|657266|...,82|90|99|85|45|82|55|90|83|94|174|100|78|144|8...,2018-11-08 12:25:35
136,RJ7WHKZYN8Z8,00045397b909e,1541686381,1,clickout item,NaN,IT,"Forli, Italy",mobile,NaN,672876|148432|82675|3590410|152441|45034|83541...,65|67|69|109|48|86|73|49|55|70|48|64|52|55|55|...,2018-11-08 14:13:01
139,1KTSH415A31G,000486f8640ae,1541699982,3,clickout item,NaN,BR,"Fortaleza, Brazil",desktop,NaN,104867|5032060|104773|127102|104634|104802|104...,60|64|74|89|48|58|70|56|66|64|48|58|66|86|301|...,2018-11-08 17:59:42
141,F2CC0TY6XRKW,00048b2736d9a,1541684412,2,interaction item image,NaN,BR,"Prado, Brazil",mobile,NaN,NaN,NaN,2018-11-08 13:40:12
165,FRRO5IGMTLVP,0004913471800,1541609283,24,clickout item,NaN,BR,"Petrópolis, Brazil",desktop,Jacuzzi (Hotel),2362196|2026065|2500900|3249862|1885513|123972...,39|90|79|65|75|63|58|77|127|76|98|130|169|83|1...,2018-11-07 16:48:03
166,YSQN2ENLJS51,000518a3ad14d,1541629997,1,clickout item,1001367,PH,"Cagayan de Oro, Philippines",desktop,NaN,1001367|5848594|1001373|2628145|2378488|313222...,33|33|37|89|13|87|18|49|24|10|40|16|19|29|12|2...,2018-11-07 22:33:17
168,8CMZ79AY4A8T,000592f5c7abe,1541683016,2,clickout item,NaN,MY,"Kota Kinabalu, Malaysia",desktop,NaN,103276|103275|103259|119306|2228070|3135218|12...,160|194|136|68|42|82|35|119|48|35|253|133|53|9...,2018-11-08 13:16:56
171,N32G2I697S13,0005f178f2542,1541699216,3,clickout item,NaN,RU,"Naberezhnye Chelny, Russia",mobile,NaN,7759496|2556340|3394866|3176300|1095224|108687...,53|39|55|50|33|117|22|12|26|32|30|42|17|36|20|...,2018-11-08 17:46:56
172,82O66X4FNQBR,0005f870c2f21,1541572380,1,clickout item,NaN,FR,"Dieppe, France",mobile,NaN,229441|49258|2798886|1659231|3515386|1501725|6...,45|89|120|89|52|51|89|44|77|70|115|40|62|40|92...,2018-11-07 06:33:00
173,2TDGFDAY1D2U,00062a0ba18df,1541561230,1,clickout item,NaN,US,"Las Vegas, USA",desktop,NaN,77124|8621|8588|1810141|8589|72426|1167514|279...,168|180|109|284|101|84|190|167|94|205|93|98|10...,2018-11-07 03:27:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3741286,DXXZUU2A4JUF,fffa850e80f11,1541691821,7,clickout item,NaN,US,"Philadelphia, USA",desktop,Focus on Distance,60137|67493|56220|63490|67636|5965756|1273290|...,371|299|331|111|423|256|494|410|148|358|153|34...,2018-11-08 15:43:41
3741287,DARYW9NQOQY8,fffa9d215b015,1541596510,1,clickout item,NaN,FR,"Istanbul, Turkey",mobile,NaN,2057626|2084924|37528|37541|37620|128839|14432...,37|50|64|263|47|103|56|83|47|79|64|67|58|53|52...,2018-11-07 13:15:10
3741288,TZ5XE944DUD3,fffaf1c39c34d,1541583389,1,clickout item,NaN,NZ,"Nelson, New Zealand",tablet,NaN,1566217|6420200|2556032|6800606|674676|2744146...,103|88|50|35|206|27|44|45|164|98|62|94|45|39|6...,2018-11-07 09:36:29
3741291,IG9SYHBLFCOH,fffb3cdffa24c,1541563974,3,clickout item,NaN,US,"Sunny Isles Beach, USA",mobile,NaN,68012|58414|1320200|56658|59822|224686|1324074...,91|65|125|130|133|51|78|165|188|164|119|195|87...,2018-11-07 04:12:54
3741299,6E2GPAMT8BN8,fffb96b676750,1541594725,8,clickout item,NaN,AR,"Villa General Belgrano, Argentina",desktop,Breakfast Included|Pet Friendly,2711420|2604312|1301750|2138878|3193478|321172...,40|34|32|57|44|30|66|46|51|32|35|56|39|44|42|3...,2018-11-07 12:45:25
3741310,9XACLXCFQDQ9,fffbe4e4a6f5d,1541610696,11,clickout item,NaN,TR,"Avanos, Turkey",mobile,NaN,7117832|1247455|3161938|7362628|897623|2038737...,67|30|59|46|724|27|39|38|40|44|26|38|70|61|99|...,2018-11-07 17:11:36
3741318,265GICQ7FJ91,fffc4e9274f7c,1541663645,8,clickout item,NaN,AU,"Melbourne, Australia",mobile,NaN,55137|54949|55144|1361410|16404|55047|1400604|...,411|484|415|520|258|382|364|523|878|283|326|22...,2018-11-08 07:54:05
3741323,G4575T85K617,fffc62338f175,1541608711,5,clickout item,2053936,BR,"Armação dos Búzios, Brazil",mobile,NaN,1104192|448986|2053936|2772562|1031604|903601|...,176|177|137|156|205|185|143|191|166|188|188|16...,2018-11-07 16:38:31
3741324,YNKRA2HBQBYV,fffc6a16af7d0,1541550291,1,clickout item,6852746,PH,"Quezon City, Philippines",mobile,NaN,6852746|2563376|2880694|3252078|3939730|203851...,90|64|34|58|99|93|157|120|97|262|68|108|242|21...,2018-11-07 00:24:51
3741325,YGV00ZR59179,fffc7c7f7f1b6,1541706921,1,clickout item,NaN,IL,"Belek, Turkey",mobile,NaN,908005|784671|1256006|486786|13528|80171|9135|...,169|93|168|108|157|66|81|217|77|124|123|410|55...,2018-11-08 19:55:21
3741331,HO6GPKJ5802B,fffcaa946f2b0,1541667771,6,interaction item image,3538232,JP,"Sendai, Japan",mobile,NaN,NaN,NaN,2018-11-08 09:02:51
3741345,21BV1WEG9GFA,fffcb835d5262,1541631882,14,clickout item,NaN,UK,"Birmingham, United Kingdom",desktop,Sort By Distance,2239640|11064768|12513|12529|12543|6470818|125...,124|417|236|173|251|170|167|295|165|242|185|20...,2018-11-07 23:04:42
3741354,UQYC654GGQ2J,fffd4213e2767,1541697153,9,clickout item,NaN,SE,"Piteå, Sweden",desktop,NaN,5503390|3854692|6418956|4009498|5494654,390|133|63|93|63,2018-11-08 17:12:33
3741355,1JHTKZHT2FPF,fffd47c879d4e,1541581878,1,clickout item,53996,DK,"Herning, Denmark",desktop,NaN,53971|53996|4995502|2326042|1328567|2520624|96...,227|241|40|70|194|113|57|48|32|77,2018-11-07 09:11:18
3741358,64I16WEN48A9,fffe4d35bf28f,1541639563,3,clickout item,NaN,CO,"Barranquilla, Colombia",mobile,NaN,9427112|9772030|7745930|8708962|7144796|7755520,44|35|30|19|25|34,2018-11-08 01:12:43
3741363,93HAOHJ3X9ZW,fffe54dd22bff,1541680271,5,clickout item,NaN,JP,"Urayasu, Japan",mobile,NaN,1320590|3247218|1131661|954519|3539818|3424700...,612|1375|548|567|1022|547|292|157|594|339|177|...,2018-11-08 12:31:11
3741367,4SJ0RY5XBIMW,ffff07dfc9efa,1541595153,4,clickout item,NaN,TH,"Lopburi, Thailand",mobile,NaN,4096550|4499792|2295286|695196|3861898|4030870...,10|16|13|24|17|13|13|11|38|53|16|13|15|16|24|2...,2018-11-07 12:52:33
3741372,CBH1TO5X96KI,ffff0ad1c618d,1541605304,5,clickout item,NaN,RU,"Abano Terme, Italy",desktop,NaN,147189|85537|345356|82951|85536|1143832|85539|...,95|147|58|92|179|106|135|84|53|235|83|237|74|7...,2018-11-07 15:41:44
3741413,RC47FIL3I4GP,ffff51afaec25,1541621776,41,clickout item,NaN,PL,"Krynica-Zdrój, Poland",desktop,NaN,2027033|2273920|1296086|1066248|1297156|111985...,47|230|93|115|110|380|146|65|89|131|120|64|79|...,2018-11-07 20:16:16
3741414,BCCI8C09QTNH,ffff65ec65bbb,1541649562,1,clickout item,NaN,MY,"Genting Highlands, Malaysia",desktop,NaN,5763948|2165594|519501|3834498|1351810|1961747...,73|91|53|61|344|143|31|21|188|87|47|23|16|21|6...,2018-11-08 03:59:22
3741441,BK24LWCQMWVB,ffffd16222b90,1541708279,27,clickout item,NaN,US,"Santa Marta, Colombia",mobile,NaN,1167004|2033381|2709816|3442272|9030086|402852...,81|50|101|77|72|31|125|68|46|107|63|234|59|48|...,2018-11-08 20:17:59
3741481,6CSR5255VX7J,j00jha5h6hquv,1541607984,40,clickout item,NaN,BR,"Ipojuca, Brazil",mobile,NaN,120786|1550525|962211|519611|1330644|503926|12...,176|167|88|88|89|84|56|69|82|44|121|68|271|57|...,2018-11-07 16:26:24
3741482,EBECR2KV1Z2A,k8sc8bupep30k,1541553955,1,clickout item,NaN,BR,"Garibaldi, Brazil",mobile,NaN,4033052|8462082|5205616|2326422|6677574|281401...,29|75|65|75|21|36|61|61|51|39|54|35|46|37|38|3...,2018-11-07 01:25:55
3741489,E6GC8Z5FJF2L,ksu05tmrdk6de,1541721521,7,clickout item,NaN,IT,"Naples, Italy",mobile,NaN,1258844|153190|896773|45930|1240467|21085|2111...,168|113|129|100|211|86|95|104|54|47|174|52|71|...,2018-11-08 23:58:41
3741491,QUA1IEG8M3R0,ld72bq2dhpub2,1541643975,2,clickout item,NaN,MX,"Tequisquiapan, Mexico",mobile,NaN,1113045|1756401|43125|2625920|2434970|4063258|...,74|85|168|283|56|101|52|80|54|30|35|48|75|37|8...,2018-11-08 02:26:15
3741526,P2NG9D9PJM3E,m35905qbciei4,1541688186,35,clickout item,NaN,BR,"Florianópolis, Brazil",mobile,NaN,929581|722186|478616|1330207|1474801|104507|10...,181|103|87|120|82|39|35|68|91|37|24|115|211|66...,2018-11-08 14:43:06
3741529,O6CNCV24819P,mc56p18be6c2g,1541611005,3,clickout item,NaN,BR,"Jaguariúna, Brazil",mobile,NaN,2898616|104826|2902348|1824817|10527680|788121...,112|62|76|771|44|46|54|50|311|146|1393|43,2018-11-07 17:16:45
3741564,2E53S73N2C5Q,mck3hrr30lm51,1541623514,35,clickout item,NaN,BR,"São Sebastião, Brazil",mobile,NaN,1083616|1826969|959381|1253344|1776301|2278030...,132|95|99|104|45|38|157|40|40|53|44|80|67|38|4...,2018-11-07 20:45:14
3741607,3Y37RU6ZVBEI,nlualuchh7j46,1541673179,43,clickout item,NaN,BR,"Ubatuba, Brazil",mobile,NaN,4399756|5513842|1056384|2030743|2771502|315224...,99|35|168|93|65|45|15|32|41|33|32|75|63|47|58|...,2018-11-08 10:32:59
3741610,KM7WDTC03BJ3,sr0atnvsbcqki,1541679213,3,change of sort order,NaN,DE,"Bad Oeynhausen, Germany",desktop,NaN,NaN,NaN,2018-11-08 12:13:33